spring.application.name=otec-primavera

# 1. LA DIRECCIÓN DE LA BODEGA (URL)
# Le decimos que busque en tu propio computador (localhost) en el puerto 3306 
# una base de datos llamada "otec_primavera_db"
spring.datasource.url=jdbc:mariadb://localhost:3306/otec_primavera_db?createDatabaseIfNotExist=true

# 2. LAS LLAVES DE LA BODEGA (Credenciales)
# Cambia "root" y la contraseña por los que uses en tu computador
spring.datasource.username=root 
spring.datasource.password=123456

# 3. EL MAESTRO CONTRATISTA (Hibernate)
# update: Le dice a Spring que revise tus clases @Entity (Curso, Estudiante)
# y si las tablas no existen en la base de datos, ¡que las cree automáticamente por ti!
spring.jpa.hibernate.ddl-auto=update

# 4. Mostrar el trabajo del contratista en la consola (Opcional pero muy útil para aprender)
# Te mostrará el código SQL que Spring genera por detrás
spring.jpa.show-sql=true